--- name:default
# maximum latency, in seconds, of the stream aligner. The aligner will start dropping samples if the difference between the last output and last input is greater than this
aggregator_max_latency: 0.3
# Altitude of Bremen in meters
altitude: 12.0
# Dip angle of Bremen in radians (equivalent to 68.05 degrees ).
dip_angle: 1.187696556
# minimum time, in s, between two sequential samples arrive on fog_samples
fog_samples_period: 0.01
# no documentation available for this property
gbiasof: 
  data: 
  - 0.0
  - 0.0
  - 0.0
# Latitude of Bremen in radians (equivalent to 53.083333 degrees).
latitude: 0.926478944
# Longitude of Bremen in radians (equivalent to 8.8 degrees).
longitude: 0.153588974
# Bremen magnetic declination in radians (equivalent to 1.35 degrees EAST).
magnetic_declination: 0.023561944
# The declination is positive when the magnetic north is east of true north
magnetic_declination_mode: 1
# minimum system time in s between two status readings
stream_aligner_status_period: 1.0
# minimum time, in s, between two sequential samples arrive on xsens_orientation
xsens_orientation_period: 0.01
