--- name:default
# no documentation available for this property
abiasof: 
  data: 
  - 0.0
  - 0.0
  - 0.0
# no documentation available for this property
accrrw: 
  data: 
  - 0.0
  - 0.0
  - 0.0
# no documentation available for this property
accrw: 
  data: 
  - 0.02236
  - 0.02236
  - 0.02236 # the resulting variance of 0.050 work weel for Dagon
# maximum latency, in seconds, of the stream aligner. The aligner will start dropping samples if the difference between the last output and last input is greater than this
aggregator_max_latency: 0.1
# Altitude of Bremen in meters
altitude: 12.0
# Time in s between position readings (aprox values for Xsens and FOG)
delta_time: 0.01
#Include (true) or exclude (false) the magnetometers values in the correction step of the filter
use_magnetometers: false
# Dip angle of Bremen in radians (equivalent to 68.05 degrees ).
dip_angle: 1.187696556
# minimum time, in s, between two sequential samples arrive on fog_samples
fog_samples_period: 0.01

# no documentation available for this property
gbiasof: 
  data: 
  - 6.911825e-03
  - 1.202073e-01
  - 0.00 #-1.881326e-06
# no documentation available for this property
gyrorrw: 
  data: 
  - 0.0
  - 0.0
  - 0.0
# no documentation available for this property
gyrorw: 
  data: 
  - 0.0006898864
  - 0.0007219069
  - 1.32e-05    #0.0005708627 #xsens
# Latitude of Bremen in radians (equivalent to 53.083333 degrees).
latitude: 0.926478944
# Longitude of Bremen in radians (equivalent to 8.8 degrees).
longitude: 0.153588974
# Bremen magnetic declination in radians (equivalent to 1.35 degrees EAST).
magnetic_declination: 0.023561944
# The declination is positive when the magnetic north is east of true north
magnetic_declination_mode: 1
# minimum system time in s between two status readings
stream_aligner_status_period: 1.0
# minimum time, in s, between two sequential samples arrive on imu_orientation
imu_orientation_period: 0.01
# minimum time, in s, between two sequential samples arrive on imu_samples
imu_samples_period: 0.01

#Random Wlak for Magnetometers
magrw:
  data: 
  - 0.0004290766
  - 9.21e-005
  - 1.06e-004

--- name:stim300
# no documentation available for this property
abiasof: 
  data: 
  - 0.0
  - 0.0
  - 0.0
# no documentation available for this property
accrrw: 
  data: 
  - 0.0
  - 0.0
  - 0.0
# no documentation available for this property
accrw: 
  data: 
  - 0.0009858879
  - 0.001097635
  - 0.001070773 
# maximum latency, in seconds, of the stream aligner. The aligner will start dropping samples if the difference between the last output and last input is greater than this
aggregator_max_latency: 0.1
# Altitude of Bremen in meters
altitude: 12.0
# Time in s between position readings (aprox values for Xsens and FOG)
delta_time: 0.008
#Include (true) or exclude (false) the magnetometers values in the correction step of the filter
use_magnetometers: false
# Dip angle of Bremen in radians (equivalent to 68.05 degrees ).
dip_angle: 1.187696556
# minimum time, in s, between two sequential samples arrive on fog_samples
fog_samples_period: 0.008

# no documentation available for this property
gbiasof: 
  data: 
  - 3.1396251683848041e-05
  - 0.0004564014580275626
  - -0.00045970399412453427
# no documentation available for this property
gyrorrw: 
  data: 
  - 0.0
  - 0.0
  - 0.0
# no documentation available for this property
gyrorw: 
  data: 
  - 4.320343e-05
  - 4.175001e-05
  - 4.060973e-05
# Latitude of Bremen in radians (equivalent to 53.083333 degrees).
latitude: 0.926478944
# Longitude of Bremen in radians (equivalent to 8.8 degrees).
longitude: 0.153588974
# Bremen magnetic declination in radians (equivalent to 1.35 degrees EAST).
magnetic_declination: 0.023561944
# The declination is positive when the magnetic north is east of true north
magnetic_declination_mode: 1
# minimum system time in s between two status readings
stream_aligner_status_period: 1.0
# minimum time, in s, between two sequential samples arrive on imu_orientation
imu_orientation_period: 0.008
# minimum time, in s, between two sequential samples arrive on imu_samples
imu_samples_period: 0.008
#Random Wlak for Magnetometers
magrw:
  data: 
  - 0.0
  - 0.0
  - 0.0





